### ISSUE TITLE
Load & Load and Filter not working

### ISSUE THREAD

**Issue by chaoscreater** [kolbasik/azure-chrome-plugin#1]
Hi there,

I can get 

> CTRL+SHIFT+F and CTRL+SHIFT+Z

 to work. I get a popup asking me to enter a search term when I use CTRL+SHIFT+F.

However, the load and load & filter don't work:
> CTRL+SHIFT+Q and CTRL+SHIFT+L

Nothing pops up and nothing happens. I do not have any extensions with keyboard shortcut set to either CTRL+SHIFT+Q or CTRL+SHIFT+L. 

I even changed the hotkey around so that CTRL+SHIFT+F will load the rows and CTRL+SHIFT+L will filter the rows and the load rows does nothing. No popup.

```
const actions = {
  "Q": function LoadAndFilterRows() {
    const term = prompt("Term?");
    term && loadAndFilterValues(term);
  },
  "F": function LoadRows() {
    loadValues();
  },
  "L": function FilterRows() {
    const term = prompt("Term?");
    term && filterValues(term);
  },
  "Z": function ResetRows() {
    resetFilter();
  }
}

```

Also, the filter seems to only work in some parts of Azure. If I go to the Subscriptions page and use the filter, it doesn't actually filter anything.

**Comment by chaoscreater** [comment]
I fixed the issues and changed the keybindings and turned it into a userscript:

https://greasyfork.org/en/scripts/486229-filter-keywords-on-azure

**Comment by kolbasik** [comment]
Hi @chaoscreater, 

Thank you very much for your interest. I was a bit surprised by your suggestions. Since I was doing it mostly for myself :)
I made PR #2 based on your ideas. I hope it will meet your needs as well. Please, let me know if it does not work for you.
